### ISSUE TITLE
why not port it to a Javascript application ? 

### ISSUE THREAD

**Issue by suvash** [foss-np/e-barnamala#4]
Since this tool requires Python wx bindings and PIL modules and the _right_ environment it seems, why not take this opportunity for rewrite and port it to an HTML/JS application with an absolutely zero setup ?

**Comment by rhoit** [comment]
Suvash dai, it will be cool to port as the web application, but we still lack programmers. Although for porting we will be requrining someone gud in both Python and Javascript! Thats why we can't say anything about porting javascript until someone takes the lead.

**Comment by hardfire** [comment]
+1 on JavaScript application.

**Comment by pravenj** [comment]
I originally wrote ebarnamala about 9-10 years ago. I have not updated it since. If people take up the challenge of programming it in JAVASCRIPT, I can help interpret the Python part. Also, with what little skill that I can support, I am willing to help design the new version in whatever language people prefer to transfer it. Over the years I have realized there are so many small things that I could have added, but slacked. There is a desperate need to make a tool like this, but support for it will be hard.  
Let me know if any plans come up.
